name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{097fa43a5a11da86f83b74c1b82aec413d46f02eb59056127fc32ba668f9ad6506-812bc7d4-94f4-4b9f-83e7-a2c78f18f9730033004089e16803}}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"          # your files are in the root
          output_location: "/"       # serve from root
          skip_app_build: true       # skip npm or yarn build
